In [1]:
import polars as pl

In [2]:
df = pl.read_csv('data/dl_data.csv')
df.tail(5)

shape: (5, 12)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Time     ┆ Date      ┆ Sender_ac ┆ Receiver_ ┆ … ┆ Receiver_ ┆ Payment_t ┆ Is_launde ┆ Launderin │
│ ---      ┆ ---       ┆ count     ┆ account   ┆   ┆ bank_loca ┆ ype       ┆ ring      ┆ g_type    │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ tion      ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆ i64       ┆ i64       ┆   ┆ ---       ┆ str       ┆ i64       ┆ str       │
│          ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10:57:01 ┆ 2023-08-2 ┆ 245393357 ┆ 519744068 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Sm │
│          ┆ 3         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:57:06 ┆ 2023-08-2 ┆ 980551017 ┆ 541660787 ┆ … ┆ UK        ┆ Debit     ┆ 0         ┆ Normal_Sm │
│          ┆ 3         ┆ 7         ┆ 8         ┆   ┆           ┆ card      ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:57:06 ┆ 2023-08-2 ┆ 728233095 ┆ 299552714 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Sm │
│          ┆ 3         ┆ 7         ┆ 9         ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:57:11 ┆ 2023-08-2 ┆ 940337377 ┆ 481281516 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Fa │
│          ┆ 3         ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ n_In      │
│ 10:57:12 ┆ 2023-08-2 ┆ 105185176 ┆ 682499483 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Fa │
│          ┆ 3         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆ n_Out     │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### NULL

In [3]:
df.null_count()

shape: (1, 12)
┌──────┬──────┬─────────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ Time ┆ Date ┆ Sender_acco ┆ Receiver_ac ┆ … ┆ Receiver_ba ┆ Payment_ty ┆ Is_launder ┆ Laundering │
│ ---  ┆ ---  ┆ unt         ┆ count       ┆   ┆ nk_location ┆ pe         ┆ ing        ┆ _type      │
│ u32  ┆ u32  ┆ ---         ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│      ┆      ┆ u32         ┆ u32         ┆   ┆ u32         ┆ u32        ┆ u32        ┆ u32        │
╞══════╪══════╪═════════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 0    ┆ 0    ┆ 0           ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
└──────┴──────┴─────────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

### DUPLICATE

In [4]:
df.filter(df.is_duplicated())

shape: (0, 12)
┌──────┬──────┬─────────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ Time ┆ Date ┆ Sender_acco ┆ Receiver_ac ┆ … ┆ Receiver_ba ┆ Payment_ty ┆ Is_launder ┆ Laundering │
│ ---  ┆ ---  ┆ unt         ┆ count       ┆   ┆ nk_location ┆ pe         ┆ ing        ┆ _type      │
│ str  ┆ str  ┆ ---         ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│      ┆      ┆ i64         ┆ i64         ┆   ┆ str         ┆ str        ┆ i64        ┆ str        │
╞══════╪══════╪═════════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
└──────┴──────┴─────────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

### SUMMARY

In [5]:
for i in df.columns:
    print(f"{i}: {df[i].n_unique()} unique values")

Time: 86284 unique values
Date: 53 unique values
Sender_account: 103772 unique values
Receiver_account: 330291 unique values
Amount: 981755 unique values
Payment_currency: 13 unique values
Received_currency: 13 unique values
Sender_bank_location: 18 unique values
Receiver_bank_location: 18 unique values
Payment_type: 7 unique values
Is_laundering: 2 unique values
Laundering_type: 28 unique values

In [6]:
for i in df.columns:
    print('======================================')
    print(f"{i}: {df[i].n_unique()} unique values")
    print(df[i].unique())

======================================
Time: 86284 unique values
shape: (86_284,)
Series: 'Time' [str]
[
	"05:06:48"
	"07:10:35"
	"05:37:09"
	"18:55:17"
	"07:21:21"
	…
	"08:57:07"
	"05:36:22"
	"04:42:38"
	"01:15:52"
	"03:12:27"
]
======================================
Date: 53 unique values
shape: (53,)
Series: 'Date' [str]
[
	"2023-07-29"
	"2023-07-25"
	"2023-07-16"
	"2023-07-26"
	"2023-08-18"
	…
	"2023-08-05"
	"2023-08-14"
	"2023-07-28"
	"2023-07-15"
	"2023-07-12"
]
======================================
Sender_account: 103772 unique values
shape: (103_772,)
Series: 'Sender_account' [i64]
[
	9018
	28511
	92172
	155434
	162832
	…
	9999156867
	9999507228
	9999699792
	9999766666
	9999819588
]
======================================
Receiver_account: 330291 unique values
shape: (330_291,)
Series: 'Receiver_account' [i64]
[
	9018
	13266
	48238
	92172
	99278
	…
	9999899663
	9999914504
	9999933179
	9999967460
	9999971095
]
======================================
Amount: 981755 unique values
shape: (981_755,)
Series: 'Amount' [f64]
[
	4.86
	5.08
	6.78
	7.19
	7.41
	…
	3.1940e6
	3507884.1
	6.2132e6
	9.2164e6
	1.2359e7
]
======================================
Payment_currency: 13 unique values
shape: (13,)
Series: 'Payment_currency' [str]
[
	"Indian rupee"
	"Pakistani rupee"
	"UK pounds"
	"Naira"
	"Swiss franc"
	…
	"Albanian lek"
	"Yen"
	"Dirham"
	"US dollar"
	"Mexican Peso"
]
======================================
Received_currency: 13 unique values
shape: (13,)
Series: 'Received_currency' [str]
[
	"Naira"
	"Euro"
	"Swiss franc"
	"Dirham"
	"Yen"
	…
	"Pakistani rupee"
	"Turkish lira"
	"Indian rupee"
	"Mexican Peso"
	"UK pounds"
]
======================================
Sender_bank_location: 18 unique values
shape: (18,)
Series: 'Sender_bank_location' [str]
[
	"USA"
	"Netherlands"
	"Nigeria"
	"France"
	"Austria"
	…
	"Turkey"
	"UK"
	"Mexico"
	"Albania"
	"Japan"
]
======================================
Receiver_bank_location: 18 unique values
shape: (18,)
Series: 'Receiver_bank_location' [str]
[
	"Austria"
	"Morocco"
	"Nigeria"
	"Japan"
	"Turkey"
	…
	"Spain"
	"Pakistan"
	"UAE"
	"UK"
	"USA"
]
======================================
Payment_type: 7 unique values
shape: (7,)
Series: 'Payment_type' [str]
[
	"ACH"
	"Credit card"
	"Cheque"
	"Debit card"
	"Cash Withdrawal"
	"Cash Deposit"
	"Cross-border"
]
======================================
Is_laundering: 2 unique values
shape: (2,)
Series: 'Is_laundering' [i64]
[
	0
	1
]
======================================
Laundering_type: 28 unique values
shape: (28,)
Series: 'Laundering_type' [str]
[
	"Normal_Cash_Deposits"
	"Cash_Withdrawal"
	"Gather-Scatter"
	"Cycle"
	"Normal_Plus_Mutual"
	…
	"Normal_single_large"
	"Layered_Fan_In"
	"Fan_Out"
	"Behavioural_Change_1"
	"Normal_Fan_In"
]

### TIMESTAMP

In [7]:
df[['Time', 'Date']].schema

Schema([('Time', String), ('Date', String)])

### XỬ LÝ TIMESTAMP VÀ LƯU FILE

In [8]:
del df

In [10]:
(
    pl.scan_csv("data/dl_data.csv")
    .with_columns([
        pl.col("Time").str.strptime(pl.Time, "%H:%M:%S"),
        pl.col("Date").str.strptime(pl.Date, "%Y-%m-%d")
    ])
    .sink_csv("data/preprocessed_data.csv")
)