In [1]:
import polars as pl

In [2]:
df = pl.read_csv('D:/HK6/ĐỒ ÁN HPC & BIG DATA/data/dl_data.csv')
df.tail(5)

shape: (5, 12)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Time     ┆ Date      ┆ Sender_ac ┆ Receiver_ ┆ … ┆ Receiver_ ┆ Payment_t ┆ Is_launde ┆ Launderin │
│ ---      ┆ ---       ┆ count     ┆ account   ┆   ┆ bank_loca ┆ ype       ┆ ring      ┆ g_type    │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ tion      ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆ i64       ┆ i64       ┆   ┆ ---       ┆ str       ┆ i64       ┆ str       │
│          ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22:14:33 ┆ 2023-07-0 ┆ 399050865 ┆ 436788759 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Sm │
│          ┆ 2         ┆ 7         ┆ 1         ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 22:14:34 ┆ 2023-07-0 ┆ 909204402 ┆ 656312259 ┆ … ┆ UK        ┆ Debit     ┆ 0         ┆ Normal_Fa │
│          ┆ 2         ┆ 2         ┆ 6         ┆   ┆           ┆ card      ┆           ┆ n_In      │
│ 22:14:34 ┆ 2023-07-0 ┆ 517836843 ┆ 330358903 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Fa │
│          ┆ 2         ┆ 1         ┆ 2         ┆   ┆           ┆           ┆           ┆ n_In      │
│ 22:14:34 ┆ 2023-07-0 ┆ 805280494 ┆ 773867091 ┆ … ┆ UK        ┆ Cheque    ┆ 0         ┆ Normal_Fa │
│          ┆ 2         ┆ 6         ┆ 8         ┆   ┆           ┆           ┆           ┆ n_In      │
│ 22:14:36 ┆ 2023-07-0 ┆ 939603385 ┆ 319700919 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Sm │
│          ┆ 2         ┆ 1         ┆ 3         ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### NULL

In [3]:
df.null_count()

shape: (1, 12)
┌──────┬──────┬─────────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ Time ┆ Date ┆ Sender_acco ┆ Receiver_ac ┆ … ┆ Receiver_ba ┆ Payment_ty ┆ Is_launder ┆ Laundering │
│ ---  ┆ ---  ┆ unt         ┆ count       ┆   ┆ nk_location ┆ pe         ┆ ing        ┆ _type      │
│ u32  ┆ u32  ┆ ---         ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│      ┆      ┆ u32         ┆ u32         ┆   ┆ u32         ┆ u32        ┆ u32        ┆ u32        │
╞══════╪══════╪═════════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 0    ┆ 0    ┆ 0           ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
└──────┴──────┴─────────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

### DUPLICATE

In [4]:
df.filter(df.is_duplicated())

shape: (0, 12)
┌──────┬──────┬─────────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ Time ┆ Date ┆ Sender_acco ┆ Receiver_ac ┆ … ┆ Receiver_ba ┆ Payment_ty ┆ Is_launder ┆ Laundering │
│ ---  ┆ ---  ┆ unt         ┆ count       ┆   ┆ nk_location ┆ pe         ┆ ing        ┆ _type      │
│ str  ┆ str  ┆ ---         ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│      ┆      ┆ i64         ┆ i64         ┆   ┆ str         ┆ str        ┆ i64        ┆ str        │
╞══════╪══════╪═════════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
└──────┴──────┴─────────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

### SUMMARY

In [5]:
for i in df.columns:
    print(f"{i}: {df[i].n_unique()} unique values")

Time: 86400 unique values
Date: 269 unique values
Sender_account: 259213 unique values
Receiver_account: 606632 unique values
Amount: 2183675 unique values
Payment_currency: 13 unique values
Received_currency: 13 unique values
Sender_bank_location: 18 unique values
Receiver_bank_location: 18 unique values
Payment_type: 7 unique values
Is_laundering: 2 unique values
Laundering_type: 28 unique values

In [6]:
for i in df.columns:
    print('======================================')
    print(f"{i}: {df[i].n_unique()} unique values")
    print(df[i].unique())

======================================
Time: 86400 unique values
shape: (86_400,)
Series: 'Time' [str]
[
	"21:49:33"
	"01:15:40"
	"08:32:15"
	"01:48:20"
	"00:35:43"
	…
	"13:24:37"
	"21:08:13"
	"09:14:11"
	"11:22:05"
	"01:13:12"
]
======================================
Date: 269 unique values
shape: (269,)
Series: 'Date' [str]
[
	"2023-01-19"
	"2023-01-25"
	"2023-07-02"
	"2022-12-06"
	"2022-11-26"
	…
	"2022-11-20"
	"2023-05-16"
	"2023-04-26"
	"2023-04-18"
	"2022-11-07"
]
======================================
Sender_account: 259213 unique values
shape: (259_213,)
Series: 'Sender_account' [i64]
[
	28511
	32095
	58673
	61549
	92172
	…
	9999765876
	9999819588
	9999862026
	9999913136
	9999986843
]
======================================
Receiver_account: 606632 unique values
shape: (606_632,)
Series: 'Receiver_account' [i64]
[
	13266
	23159
	28511
	48238
	58673
	…
	9999886174
	9999933179
	9999958143
	9999967460
	9999971095
]
======================================
Amount: 2183675 unique values
shape: (2_183_675,)
Series: 'Amount' [f64]
[
	3.73
	4.23
	4.5
	4.57
	4.59
	…
	9.3481e6
	9939367.7
	1.0267e7
	1.1837e7
	1.2618e7
]
======================================
Payment_currency: 13 unique values
shape: (13,)
Series: 'Payment_currency' [str]
[
	"Dirham"
	"Pakistani rupee"
	"UK pounds"
	"Yen"
	"Moroccan dirham"
	…
	"US dollar"
	"Indian rupee"
	"Turkish lira"
	"Euro"
	"Naira"
]
======================================
Received_currency: 13 unique values
shape: (13,)
Series: 'Received_currency' [str]
[
	"Dirham"
	"Turkish lira"
	"Yen"
	"Swiss franc"
	"Pakistani rupee"
	…
	"Euro"
	"UK pounds"
	"US dollar"
	"Moroccan dirham"
	"Naira"
]
======================================
Sender_bank_location: 18 unique values
shape: (18,)
Series: 'Sender_bank_location' [str]
[
	"USA"
	"Nigeria"
	"France"
	"UK"
	"Japan"
	…
	"Netherlands"
	"Mexico"
	"Spain"
	"UAE"
	"Pakistan"
]
======================================
Receiver_bank_location: 18 unique values
shape: (18,)
Series: 'Receiver_bank_location' [str]
[
	"Japan"
	"Germany"
	"Italy"
	"USA"
	"Mexico"
	…
	"Switzerland"
	"Nigeria"
	"Austria"
	"France"
	"UAE"
]
======================================
Payment_type: 7 unique values
shape: (7,)
Series: 'Payment_type' [str]
[
	"Credit card"
	"Cross-border"
	"Cash Withdrawal"
	"Cash Deposit"
	"ACH"
	"Debit card"
	"Cheque"
]
======================================
Is_laundering: 2 unique values
shape: (2,)
Series: 'Is_laundering' [i64]
[
	0
	1
]
======================================
Laundering_type: 28 unique values
shape: (28,)
Series: 'Laundering_type' [str]
[
	"Behavioural_Change_1"
	"Normal_Cash_Deposits"
	"Behavioural_Change_2"
	"Layered_Fan_Out"
	"Cycle"
	…
	"Over-Invoicing"
	"Scatter-Gather"
	"Fan_Out"
	"Fan_In"
	"Single_large"
]

### TIMESTAMP

In [7]:
df[['Time', 'Date']].schema

Schema([('Time', String), ('Date', String)])

### XỬ LÝ TIMESTAMP VÀ LƯU FILE

In [8]:
del df

In [10]:
(
    pl.scan_csv("D:/HK6/ĐỒ ÁN HPC & BIG DATA/data/dl_data.csv")
    .with_columns([
        pl.col("Time").str.strptime(pl.Time, "%H:%M:%S"),
        pl.col("Date").str.strptime(pl.Date, "%Y-%m-%d")
    ])
    .sink_csv("D:/HK6/ĐỒ ÁN HPC & BIG DATA/data/preprocessed_data.csv")
)